"""Pydantic models for authentication events, alerts, and cases.

This module defines the core data structures used throughout the
Log Detective pipeline.
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class AuthEvent(BaseModel):
    """Normalized authentication event from any log source.
    
    Attributes:
        event_id: Unique identifier for this event.
        ts: Timestamp in UTC.
        provider: Log source (e.g., "azure", "cloudtrail", "custom").
        user: User identifier (email or username).
        action: Descriptive action (e.g., "login_attempt"). NOT the source of truth.
        source_ip: IP address of the authentication attempt.
        country: Country code or name (if available).
        city: City name (if available).
        lat: Latitude for geo-calculations.
        lon: Longitude for geo-calculations.
        user_agent: Browser/client user agent string.
        device_id: Device identifier. Derived from UA+IP if not present.
        auth_method: Authentication method (password, mfa, oauth, etc.).
        result: "success" or "failure" - THIS IS THE SOURCE OF TRUTH.
        failure_reason: Reason for failure (if applicable).
        raw: Original raw event data for reference.
    """
    
    event_id: str
    ts: datetime
    provider: str = "custom"
    user: str
    action: str = "login_attempt"
    source_ip: str
    country: str | None = None
    city: str | None = None
    lat: float | None = None
    lon: float | None = None
    user_agent: str | None = None
    device_id: str | None = None
    auth_method: str | None = None
    result: Literal["success", "failure"]
    failure_reason: str | None = None
    raw: dict = Field(default_factory=dict)
    
    class Config:
        """Pydantic configuration."""
        frozen = False
        extra = "ignore"


class Alert(BaseModel):
    """Security alert generated by a detector.
    
    Attributes:
        alert_id: Unique identifier for this alert.
        detector: Name of the detector that generated this alert.
        ts_start: Start of the detection window (min timestamp from related events).
        ts_end: End of the detection window (max timestamp from related events).
        user: User associated with this alert.
        severity: Alert severity level.
        score: Numeric score from 0-100.
        title: Short title for the alert.
        description: Detailed description of what was detected.
        evidence: Evidence dictionary with standardized keys:
            - ips: list[str] - All IPs involved
            - device_ids: list[str] - All device IDs involved
            - countries: list[str] - All countries involved
            - (plus detector-specific keys)
        mitre: List of MITRE ATT&CK technique IDs (optional).
        related_event_ids: List of event IDs that triggered this alert.
    """
    
    alert_id: str
    detector: str
    ts_start: datetime
    ts_end: datetime
    user: str
    severity: Literal["low", "medium", "high", "critical"]
    score: int = Field(ge=0, le=100)
    title: str
    description: str
    evidence: dict = Field(default_factory=dict)
    mitre: list[str] = Field(default_factory=list)
    related_event_ids: list[str] = Field(default_factory=list)
    
    class Config:
        """Pydantic configuration."""
        frozen = False


class Case(BaseModel):
    """Security case (incident) composed of correlated alerts.
    
    Attributes:
        case_id: Unique identifier for this case.
        user: Primary user associated with this case.
        ts_start: Earliest timestamp across all alerts.
        ts_end: Latest timestamp across all alerts.
        alerts: List of alerts in this case.
        overall_severity: Calculated case severity.
        overall_score: Calculated case score (0-100).
        summary: Human-readable summary paragraph.
        recommended_actions: List of recommended response actions.
        timeline: Ordered list of key events from all related alerts.
    """
    
    case_id: str
    user: str
    ts_start: datetime
    ts_end: datetime
    alerts: list[Alert] = Field(default_factory=list)
    overall_severity: Literal["low", "medium", "high", "critical"] = "low"
    overall_score: int = Field(ge=0, le=100, default=0)
    summary: str = ""
    recommended_actions: list[str] = Field(default_factory=list)
    timeline: list[AuthEvent] = Field(default_factory=list)
    
    class Config:
        """Pydantic configuration."""
        frozen = False
